export type Place = {
  slug: string;
  name: string;
  region: string;
  category: string;
  image: string;
  alt: string;
  rating: string;
  detail: string;
  intro: string;
  experience: string;
  bestTime: string;
  localTip: string;
};

export const places: Place[] = [
  {
    slug: "lofoten-islands",
    name: "Lofoten Islands",
    region: "Nordland, Northern Norway",
    category: "Arctic",
    image: "/images/cabin.jpg",
    alt: "A cozy cabin beneath Norway's snow-covered mountains",
    rating: "4.98",
    detail: "Fisherman villages · Midnight sun",
    intro: "Where steep mountain peaks meet fishing villages and open sea, Lofoten is made for taking the scenic route. Give the islands a little time and the changing light becomes part of the journey.",
    experience: "Follow the coastal roads between small harbours, stop for a quiet beach walk, and leave an evening open for the long Arctic light.",
    bestTime: "May to August for long bright days; September to March for dark skies and a chance of seeing the aurora.",
    localTip: "The islands are more rewarding when you stay a few nights in one place. Check local conditions before setting out on mountain trails.",
  },
  {
    slug: "bergen-and-the-fjords",
    name: "Bergen & the Fjords",
    region: "Vestland, Western Norway",
    category: "Fjords",
    image: "/images/bergen.jpg",
    alt: "A deep fjord winding through a green Norwegian valley",
    rating: "4.96",
    detail: "Fjord cruises · Mountain trails",
    intro: "A lively harbour city makes a natural beginning to a journey into Western Norway. From Bergen, the landscape opens into deep fjords, green valleys, and villages that reward a slower pace.",
    experience: "Wander the old harbour in the morning, then take a boat or train out towards the fjords. A short hillside walk is a lovely way to see the city from above.",
    bestTime: "May to September for long days, mountain walks, and easier connections into the fjords.",
    localTip: "The weather can change quickly between the coast and the mountains. Keep a light waterproof layer handy, even on a clear morning.",
  },
  {
    slug: "tromso",
    name: "Tromsø",
    region: "Troms, Northern Norway",
    category: "Arctic",
    image: "/images/tromso.jpg",
    alt: "Snowy peaks rising above a calm Arctic fjord",
    rating: "4.94",
    detail: "Northern lights · Arctic wildlife",
    intro: "Tromsø brings Arctic nature and a welcoming city together above the Arctic Circle. Harbour life, mountain views, and wide northern skies make it a memorable base in every season.",
    experience: "Explore the waterfront and local museums by day, then head beyond the city lights for a quiet evening under the Arctic sky.",
    bestTime: "September to March for polar nights and aurora season; June to August for the midnight sun and outdoor days.",
    localTip: "Plan more than one evening for aurora watching. Clear skies matter, and no forecast can guarantee a display.",
  },
  {
    slug: "oslo",
    name: "Oslo",
    region: "Oslo, Eastern Norway",
    category: "Cities",
    image: "/images/oslo.jpg",
    alt: "A peaceful lakeside hideaway surrounded by Norwegian forest",
    rating: "4.91",
    detail: "Design & culture · Island hopping",
    intro: "Oslo is a city where thoughtful design and everyday nature sit close together. A few minutes can take you from galleries and cafés to the waterfront or the quiet paths of the forest.",
    experience: "Spend the morning around the harbour and its museums, then take a local ferry or head into the green hills for a calmer afternoon.",
    bestTime: "May to September for open-air cafés, island ferries, and long walks; winter brings a cosy city atmosphere.",
    localTip: "Use local public transport to reach the forests and waterfront. The city is easy to explore without a car.",
  },
  {
    slug: "geirangerfjord",
    name: "Geirangerfjord",
    region: "Møre og Romsdal, Western Norway",
    category: "Fjords",
    image: "/images/hideaway.jpg",
    alt: "A quiet wooden cabin beside a forest-framed Norwegian lake",
    rating: "4.99",
    detail: "Waterfalls · Scenic drives",
    intro: "Geirangerfjord is a landscape of steep green walls, falling waterfalls, and water that seems to disappear around every bend. Its scale is best appreciated when you pause and let the view unfold.",
    experience: "See the fjord from the water, then take a gentle walk to a viewpoint above the village. The changing angle reveals a different landscape at every turn.",
    bestTime: "May to September for boat trips and open scenic roads; shoulder-season visits are quieter but weather dependent.",
    localTip: "Arrive early for popular viewpoints and check road and ferry conditions before travelling through the area.",
  },
  {
    slug: "senja-island",
    name: "Senja Island",
    region: "Troms, Northern Norway",
    category: "Arctic",
    image: "/images/lodge.jpg",
    alt: "A remote lodge glowing under a starry northern sky",
    rating: "4.97",
    detail: "Coastal hikes · Quiet coves",
    intro: "Senja gathers dramatic Arctic coastline into a quieter island escape. Fishing villages, open sea, and mountain silhouettes make even a short drive feel like a discovery.",
    experience: "Take the scenic coastal route, pause at small harbour villages, and choose a short marked trail for a close-up look at the island's changing shoreline.",
    bestTime: "June to September for hiking and long light; winter brings a quieter coast and dark skies.",
    localTip: "Distances and weather can make journeys slower than expected. Keep plans flexible and check local trail conditions.",
  },
  {
    slug: "alesund",
    name: "Ålesund",
    region: "Møre og Romsdal, Western Norway",
    category: "Cities",
    image: "/images/platform.jpg",
    alt: "A wooden boat floating on a still lake beneath steep green mountains",
    rating: "4.95",
    detail: "Art nouveau streets · Ocean views",
    intro: "Set between islands and mountains, Ålesund is a graceful coastal town with an unmistakable architectural character. It is a lovely place to slow down between fjord adventures.",
    experience: "Walk the harbour and art nouveau streets, then climb to the town viewpoint for a broad panorama of rooftops, islands, and water.",
    bestTime: "May to September for longer days, boat trips, and coastal walks.",
    localTip: "The town centre is compact and easy to explore on foot. Bring a light rain layer for the exposed viewpoint.",
  },
  {
    slug: "trondheim",
    name: "Trondheim",
    region: "Trøndelag, Central Norway",
    category: "Cities",
    image: "/images/trondheim.jpg",
    alt: "Gentle blue ocean waves under a pale sky",
    rating: "4.92",
    detail: "Historic wharves · Nordic food",
    intro: "Trondheim pairs a rich historic centre with an easy, youthful energy. Its colourful riverfront and relaxed cafés make it a city best explored one pleasant walk at a time.",
    experience: "Follow the river through the old wharf district, cross the colourful bridges, and stop at a neighbourhood bakery before visiting the cathedral.",
    bestTime: "May to September for riverside walks and outdoor dining; winter is quieter and full of cosy cafés.",
    localTip: "The central sights are close together, so leave room for wandering down side streets rather than planning every stop.",
  },
  {
    slug: "stavanger",
    name: "Stavanger",
    region: "Rogaland, Southwestern Norway",
    category: "Cities",
    image: "/images/stavanger.jpg",
    alt: "A wide alpine valley framed by snow-capped mountains",
    rating: "4.93",
    detail: "Old town charm · Coastal culture",
    intro: "Stavanger blends a welcoming old town with a lively harbour and easy access to the coast. It is an inviting place to pair relaxed city days with bigger outdoor adventures.",
    experience: "Wander the quiet streets of Gamle Stavanger, find a table near the harbour, and set aside a day for the landscapes around Lysefjord.",
    bestTime: "May to September for milder weather and hiking; check local conditions before planning exposed mountain routes.",
    localTip: "Popular hikes need a little planning. Start early, use marked routes, and never underestimate changing mountain weather.",
  },
  {
    slug: "flam-and-aurlandsfjord",
    name: "Flåm & Aurlandsfjord",
    region: "Vestland, Western Norway",
    category: "Fjords",
    image: "/images/flam.jpg",
    alt: "Lush green fern leaves filling the frame",
    rating: "4.97",
    detail: "Scenic railway · Fjord kayaking",
    intro: "Flåm is a small village set deep in a grand fjord landscape. The best moments here often happen between the big excursions: a quiet stretch beside the water or a slow ride through the valley.",
    experience: "Take the scenic railway, explore the fjord by boat, or choose a gentle valley walk and linger at the viewpoints along the way.",
    bestTime: "May to September for boat trips, green valleys, and longer daylight.",
    localTip: "Reserve popular trains and boat journeys in advance, but leave some unplanned time to explore the village on foot.",
  },
  {
    slug: "sognefjord",
    name: "Sognefjord",
    region: "Vestland, Western Norway",
    category: "Fjords",
    image: "/images/sognefjord.jpg",
    alt: "A tall granite mountain rising above a meadow and pine forest",
    rating: "4.98",
    detail: "Orchard villages · Glacier walks",
    intro: "Norway's longest fjord reaches deep into the heart of Western Norway. Around its many branches, small villages, orchards, and mountain scenery invite you to explore beyond a single viewpoint.",
    experience: "Choose a village as a base, take a local ferry between fjord communities, and make time for an easy walk through the surrounding landscape.",
    bestTime: "May to September for green valleys, open routes, and ferry connections.",
    localTip: "The fjord is vast, so choose a region to explore instead of trying to see every branch in one trip.",
  },
  {
    slug: "naeroyfjord",
    name: "Nærøyfjord",
    region: "Vestland, Western Norway",
    category: "Fjords",
    image: "/images/naeroyfjord.jpg",
    alt: "Layered mountain ridges fading into a warm evening sky",
    rating: "4.96",
    detail: "UNESCO-listed waters · Quiet cruises",
    intro: "Nærøyfjord is narrow, peaceful, and surrounded by mountains that rise almost straight from the water. A journey through it feels intimate, even in a landscape built on a grand scale.",
    experience: "Take a small boat through the fjord and watch for waterfalls, farms, and tiny settlements tucked into the steep valley sides.",
    bestTime: "May to September for boat journeys and long daylight; spring brings high water to the waterfalls.",
    localTip: "Choose a quieter departure if possible and bring an extra layer for the cool air on the water.",
  },
  {
    slug: "hardangerfjord",
    name: "Hardangerfjord",
    region: "Vestland, Western Norway",
    category: "Fjords",
    image: "/images/hardangerfjord.jpg",
    alt: "A sunlit path winding through a quiet evergreen forest",
    rating: "4.95",
    detail: "Spring blossoms · Waterfall trails",
    intro: "Hardangerfjord is known for orchards, waterfalls, and a softer, greener kind of fjord scenery. In every season, the meeting of mountains and cultivated valleys gives the region its own gentle rhythm.",
    experience: "Take a scenic drive between small communities, stop at a waterfall, and taste local produce when it is in season.",
    bestTime: "May for blossom season; June to September for valley walks and scenic drives.",
    localTip: "Check seasonal opening dates for farm shops and viewpoints before setting out, especially early and late in the year.",
  },
  {
    slug: "preikestolen",
    name: "Preikestolen",
    region: "Rogaland, Southwestern Norway",
    category: "Fjords",
    image: "/images/preikestolen.jpg",
    alt: "A star-filled night sky above snow-covered mountain peaks",
    rating: "4.94",
    detail: "Clifftop hikes · Lysefjord views",
    intro: "The trail to Preikestolen leads to one of Norway's most striking views above Lysefjord. The hike is as much about the changing mountain terrain along the way as the famous cliff at the end.",
    experience: "Start with a steady, unhurried walk and take breaks at the viewpoints. At the top, give yourself time to appreciate the fjord from a safe distance.",
    bestTime: "May to October, depending on weather and trail conditions. Winter visits require suitable experience and equipment.",
    localTip: "Wear sturdy shoes, bring water and warm layers, and check the official trail and weather updates before you go.",
  },
  {
    slug: "jotunheimen-national-park",
    name: "Jotunheimen National Park",
    region: "Innlandet, Eastern Norway",
    category: "Nature",
    image: "/images/jotunheimen.jpg",
    alt: "The sun setting behind layers of forested mountain ridges",
    rating: "4.98",
    detail: "Alpine peaks · Long-distance trails",
    intro: "Jotunheimen is a world of high peaks, glacial lakes, and trails that invite you to step beyond the everyday. With a little preparation, even a gentle walk can feel like a true mountain escape.",
    experience: "Choose a route suited to the day's conditions, take your time beside the lakes, and stay overnight if you want to experience the quiet of the mountains.",
    bestTime: "Late June to September for most marked hiking routes; snow and weather affect access each year.",
    localTip: "Mountain weather changes quickly. Check the forecast and trail conditions, carry suitable layers, and choose a route that matches your experience.",
  },
  {
    slug: "rondane-national-park",
    name: "Rondane National Park",
    region: "Innlandet, Eastern Norway",
    category: "Nature",
    image: "/images/rondane.jpg",
    alt: "Golden wildflowers growing beneath a clear blue sky",
    rating: "4.93",
    detail: "Open plateaus · Reindeer country",
    intro: "Rondane offers open mountain plateaus and a wonderful sense of space. The scenery feels quiet and expansive, with marked paths that make it easy to find a walk at your own pace.",
    experience: "Follow a well-marked valley trail, pause for a picnic with a mountain view, and keep an eye out for the changing colours of the highland landscape.",
    bestTime: "July to September for most summer walks; winter conditions arrive early at higher elevations.",
    localTip: "This is a wild reindeer area. Keep your distance from wildlife and follow local guidance on trails and conservation.",
  },
  {
    slug: "north-cape",
    name: "North Cape",
    region: "Finnmark, Northern Norway",
    category: "Arctic",
    image: "/images/north-cape.jpg",
    alt: "Sunlight falling across a forested mountain landscape",
    rating: "4.96",
    detail: "Arctic cliffs · Midnight sun",
    intro: "At Europe's far northern edge, the North Cape feels wonderfully remote. Ocean, sky, and open tundra stretch into a horizon that changes with every shift in the weather.",
    experience: "Take time on the coastal road, explore nearby fishing communities, and wait for the light to change over the cliffs.",
    bestTime: "May to July for the midnight sun; September to March for dark Arctic skies, weather permitting.",
    localTip: "Wind and visibility can change quickly at the cape. Dress warmly and check road conditions before travelling.",
  },
  {
    slug: "alta",
    name: "Alta",
    region: "Finnmark, Northern Norway",
    category: "Arctic",
    image: "/images/alta.jpg",
    alt: "A quiet road passing through dramatic red rock formations",
    rating: "4.92",
    detail: "Northern lights · Sámi heritage",
    intro: "Alta offers an open, grounded introduction to life in Arctic Norway. Long river valleys, traces of ancient culture, and wide northern skies give the area a character all its own.",
    experience: "Learn about the region's Sámi heritage, visit the rock art at Alta Museum, and leave an evening free to watch the sky.",
    bestTime: "September to March for aurora opportunities; June to August for bright nights and outdoor exploring.",
    localTip: "Choose locally guided experiences to learn about the region with care and respect for the communities who live here.",
  },
  {
    slug: "vesteralen-islands",
    name: "Vesterålen Islands",
    region: "Nordland, Northern Norway",
    category: "Arctic",
    image: "/images/vesteralen.jpg",
    alt: "Snow-dusted mountains reflected in a calm alpine lake",
    rating: "4.95",
    detail: "Whale watching · Coastal roads",
    intro: "Vesterålen is an inviting Arctic island escape, where quiet fishing villages and open coastline make room for unhurried exploration. It feels spacious even when you are never far from a welcoming harbour.",
    experience: "Follow the coastal road, stop at small communities, and join a responsible local wildlife tour if conditions allow.",
    bestTime: "May to September for coastal journeys and hiking; wildlife experiences vary throughout the year.",
    localTip: "Give yourself time between villages and book wildlife tours with operators who follow responsible viewing practices.",
  },
  {
    slug: "roros",
    name: "Røros",
    region: "Trøndelag, Central Norway",
    category: "Cities",
    image: "/images/roros.jpg",
    alt: "A turquoise mountain lake with a small wooden boat",
    rating: "4.94",
    detail: "UNESCO heritage · Timber streets",
    intro: "Røros is a historic mountain town with wooden streets, colourful old buildings, and an atmosphere that feels a world away from the coast. Its heritage is best discovered slowly, one lane at a time.",
    experience: "Walk the historic centre, visit local workshops, and settle in for a meal made with ingredients from the surrounding region.",
    bestTime: "June to September for easier walking; winter brings snow-covered streets and a particularly cosy feel.",
    localTip: "Many of the old buildings are still homes and workplaces. Be considerate, and explore the town on foot.",
  },
  {
    slug: "hardangervidda",
    name: "Hardangervidda",
    region: "Vestland, Western Norway",
    category: "Nature",
    image: "/images/hardangervidda.jpg",
    alt: "A lone hiker standing on a rocky ridge above a green valley",
    rating: "4.91",
    detail: "Highland trails · Vast open skies",
    intro: "Hardangervidda is a vast mountain plateau of open horizons and quiet trails. The feeling of space here is immediate, and even a short walk can bring a welcome sense of stillness.",
    experience: "Pick a marked route for the weather and your experience, then let the wide landscape set the pace. Stop often; the details are easy to miss when rushing.",
    bestTime: "July to September for most summer hiking; weather and snow can affect routes outside this period.",
    localTip: "Plan for exposed conditions, carry navigation and warm layers, and check local advice before setting out across the plateau.",
  },
];

export function getPlace(slug: string) {
  return places.find((place) => place.slug === slug);
}
